import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://www.lastminutegifts.co.ke"),
  title: "Last-Minute Gifts Kenya | Same-Day Gift Delivery",
  description:
    "Order beautiful last-minute gifts with same-day delivery across Kenya.",

  keywords: [
    "last minute gifts",
    "gift delivery Kenya",
    "same day gifts",
    "flowers Kenya",
    "romantic gifts",
    "gift shop Kenya",
  ],

  openGraph: {
    title: "Last-Minute Gifts Kenya",
    description:
      "Order beautiful last-minute gifts with same-day delivery across Kenya.",
    url: "https://www.lastminutegifts.co.ke",
    siteName: "Last-Minute Gifts",
    images: [
      {
        url: "/logo.jpeg",
        width: 1200,
        height: 630,
        alt: "Last-Minute Gifts",
      },
    ],
    locale: "en_KE",
    type: "website",
  },

  twitter: {
    card: "summary_large_image",
    title: "Last-Minute Gifts Kenya",
    description:
      "Order beautiful last-minute gifts with same-day delivery across Kenya.",
    images: ["/logo.jpeg"],
  },

  icons: {
    icon: "/favicon.ico",
    apple: "/logo.jpeg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <script src="https://js.paystack.co/v1/inline.js" async />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
// export const metadata: Metadata = {
//   metadataBase: new URL("https://lastminutegifts.co.ke"),
//   title: "Last-Minute Gifts Kenya | Same-Day Gift Delivery",
//   description:
//     "Order beautiful last-minute gifts with same-day delivery across Kenya.",
//   keywords: [
//     "last minute gifts",
//     "gift delivery kenya",
//     "same day gifts",
//     "flowers kenya",
//     "romantic gifts",
//     "gift shop kenya",
//   ],
//   openGraph: {
//     title: "Last-Minute Gifts Kenya",
//     description:
//       "Same-day gift delivery across Kenya.",
//     url: "https://lastminutegifts.co.ke",
//     siteName: "Last-Minute Gifts",
//     type: "website",
//   },
//   twitter: {
//     card: "summary_large_image",
//     title: "Last-Minute Gifts Kenya",
//     description:
//       "Same-day gift delivery across Kenya.",
//   },
// };
// // import type { Metadata } from "next";
// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata: Metadata = {
// //   title: "Last-Minute Gifts Kenya | Same-Day Gift Delivery",
// //   description: "Order last-minute gifts with same-day delivery across Kenya.",
// //   metadataBase: new URL("https://lastminutegifts.co.ke"),
// // };
// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html
// //       lang="en"
// //       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
// //     >
// //       <head>
// //         {/* Paystack Inline Checkout Script */}
// //         <script src="https://js.paystack.co/v1/inline.js" async></script>
// //       </head>
// //       <body className="min-h-full flex flex-col">{children}</body>
// //     </html>
// //   );
// // }
// // // import type { Metadata } from "next";
// // // import { Geist, Geist_Mono } from "next/font/google";
// // // import "./globals.css";

// // // const geistSans = Geist({
// // //   variable: "--font-geist-sans",
// // //   subsets: ["latin"],
// // // });

// // // const geistMono = Geist_Mono({
// // //   variable: "--font-geist-mono",
// // //   subsets: ["latin"],
// // // });

// // // export const metadata: Metadata = {
// // //   title: "Create Next App",
// // //   description: "Generated by create next app",
// // // };

// // // export default function RootLayout({
// // //   children,
// // // }: Readonly<{
// // //   children: React.ReactNode;
// // // }>) {
// // //   return (
// // //     <html
// // //       lang="en"
// // //       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
// // //     >
// // //       <body className="min-h-full flex flex-col">{children}</body>
// // //     </html>
// // //   );
// // // }
